services:
  pigeon-pod:
    build: .
    image: pigeon-pod:latest
    restart: unless-stopped
    container_name: pigeon-pod
    ports:
      - '8834:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/pigeon-pod.db
      - PIGEON_LOG_FILE=/data/logs/pigeon-pod.log
    volumes:
      # Application data: SQLite database, logs, runtime configurations
      - ./data:/data
      # Optional: Separate media storage (audio & video) onto a different disk or media share
      # - /path/to/media/audio:/data/audio
      # - /path/to/media/video:/data/video
