// Standard podcast language options compliant with RSS 2.0 and Apple Podcasts specifications (ISO 639-1 / RFC 5646)
export const DEFAULT_PODCAST_LANGUAGE = 'en';

export const PODCAST_LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English (en)' },
  { value: 'en-us', label: 'English - United States (en-us)' },
  { value: 'en-gb', label: 'English - United Kingdom (en-gb)' },
  { value: 'en-ca', label: 'English - Canada (en-ca)' },
  { value: 'en-au', label: 'English - Australia (en-au)' },
  { value: 'zh-cn', label: '中文 - 简体 (zh-cn)' },
  { value: 'zh-tw', label: '中文 - 繁體 (zh-tw)' },
  { value: 'zh-hk', label: '中文 - 香港 (zh-hk)' },
  { value: 'zh', label: '中文 (zh)' },
  { value: 'ja', label: '日本語 (ja)' },
  { value: 'ko', label: '한국어 (ko)' },
  { value: 'es', label: 'Español (es)' },
  { value: 'es-es', label: 'Español - España (es-es)' },
  { value: 'es-419', label: 'Español - Latinoamérica (es-419)' },
  { value: 'fr', label: 'Français (fr)' },
  { value: 'fr-ca', label: 'Français - Canada (fr-ca)' },
  { value: 'de', label: 'Deutsch (de)' },
  { value: 'de-de', label: 'Deutsch - Deutschland (de-de)' },
  { value: 'it', label: 'Italiano (it)' },
  { value: 'pt', label: 'Português (pt)' },
  { value: 'pt-br', label: 'Português - Brasil (pt-br)' },
  { value: 'ru', label: 'Русский (ru)' },
  { value: 'ar', label: 'العربية (ar)' },
  { value: 'hi', label: 'हिन्दी (hi)' },
  { value: 'nl', label: 'Nederlands (nl)' },
  { value: 'pl', label: 'Polski (pl)' },
  { value: 'tr', label: 'Türkçe (tr)' },
  { value: 'vi', label: 'Tiếng Việt (vi)' },
  { value: 'th', label: 'ไทย (th)' },
  { value: 'id', label: 'Bahasa Indonesia (id)' },
  { value: 'sv', label: 'Svenska (sv)' },
  { value: 'uk', label: 'Українська (uk)' },
];
