#!/usr/bin/env bash
set -euo pipefail

# Publish flow:
# 1. Resolve the main repository root and the local wiki draft directory.
# 2. Run the draft validation script before touching the wiki repository.
# 3. Derive the GitHub wiki remote URL from the configured git remote.
# 4. Clone the wiki repo into a temporary workdir, or reuse a caller-provided workdir.
# 5. Replace top-level wiki markdown files with the validated local draft files.
# 6. Commit and push the resulting wiki repository state.
#
# The script treats dev-docs/wiki-drafts as the single source of truth for wiki pages.
# It intentionally does a full top-level markdown replacement instead of incremental sync.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Local source of truth for wiki content.
SOURCE_DIR="$REPO_ROOT/dev-docs/wiki-drafts"

# Pre-publish validation gate. Publishing stops immediately if this script fails.
CHECK_SCRIPT="$SCRIPT_DIR/check-wiki-drafts.sh"

# Git remote used to derive the wiki repository URL.
# Example:
#   git@github.com:aizhimou/PigeonPod.git
# becomes:
#   git@github.com:aizhimou/PigeonPod.wiki.git
REMOTE_NAME="origin"

# Default commit message for wiki sync commits.
COMMIT_MESSAGE="docs: sync wiki content"

# Optional persistent wiki checkout provided by the caller.
# If empty, the script creates and later deletes a temporary workdir.
WORKDIR=""

# When set, keep the temporary workdir after completion for inspection/debugging.
KEEP_WORKDIR=0

# When set, prepare and commit locally but do not push to GitHub.
DRY_RUN=0

function usage() {
  cat <<'EOF'
Usage: scripts/publish-wiki.sh [options]

Sync markdown files from dev-docs/wiki-drafts into the GitHub wiki repository.

Options:
  --source <dir>       Source directory. Default: dev-docs/wiki-drafts
  --remote <name>      Git remote name used to derive the wiki URL. Default: origin
  --workdir <dir>      Reuse a specific local working directory instead of a temp dir
  --message <msg>      Commit message. Default: "docs: sync wiki content"
  --dry-run            Prepare the wiki worktree and commit locally, but do not push
  --keep-workdir       Keep the temporary workdir after the script exits
  --help               Show this help
EOF
}

function log() {
  printf '[publish-wiki] %s\n' "$*"
}

function fail() {
  printf '[publish-wiki] ERROR: %s\n' "$*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source)
      [[ $# -ge 2 ]] || fail "--source requires a value"
      SOURCE_DIR="$2"
      shift 2
      ;;
    --remote)
      [[ $# -ge 2 ]] || fail "--remote requires a value"
      REMOTE_NAME="$2"
      shift 2
      ;;
    --workdir)
      [[ $# -ge 2 ]] || fail "--workdir requires a value"
      WORKDIR="$2"
      shift 2
      ;;
    --message)
      [[ $# -ge 2 ]] || fail "--message requires a value"
      COMMIT_MESSAGE="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --keep-workdir)
      KEEP_WORKDIR=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
done

[[ -d "$REPO_ROOT/.git" ]] || fail "Run this script from inside the repository checkout."
[[ -d "$SOURCE_DIR" ]] || fail "Source directory does not exist: $SOURCE_DIR"
[[ -f "$SOURCE_DIR/Home.md" ]] || fail "Source directory must contain Home.md"
[[ -x "$CHECK_SCRIPT" ]] || fail "Wiki draft check script is missing or not executable: $CHECK_SCRIPT"

if ! command -v git >/dev/null 2>&1; then
  fail "git is required"
fi

ORIGIN_URL="$(git -C "$REPO_ROOT" remote get-url "$REMOTE_NAME" 2>/dev/null || true)"
[[ -n "$ORIGIN_URL" ]] || fail "Failed to resolve git remote '$REMOTE_NAME'"
WIKI_URL="${ORIGIN_URL%.git}.wiki.git"

TEMP_WORKDIR=""
if [[ -z "$WORKDIR" ]]; then
  # Default mode: create an isolated temporary wiki checkout so each run starts clean.
  TEMP_WORKDIR="$(mktemp -d)"
  WORKDIR="$TEMP_WORKDIR/wiki"
fi

function cleanup() {
  # Only remove the autogenerated temp workdir.
  # Caller-provided workdirs are left untouched.
  if [[ -n "$TEMP_WORKDIR" && "$KEEP_WORKDIR" -eq 0 ]]; then
    rm -rf "$TEMP_WORKDIR"
  fi
}
trap cleanup EXIT

log "Repository root: $REPO_ROOT"
log "Source directory: $SOURCE_DIR"
log "Wiki URL: $WIKI_URL"
log "Running wiki draft checks..."
"$CHECK_SCRIPT" --source "$SOURCE_DIR"

if [[ -e "$WORKDIR" ]]; then
  # Reuse mode: update the existing local wiki checkout and keep its remote strict.
  [[ -d "$WORKDIR/.git" ]] || fail "Workdir exists but is not a git repository: $WORKDIR"
  EXISTING_REMOTE="$(git -C "$WORKDIR" remote get-url origin 2>/dev/null || true)"
  [[ "$EXISTING_REMOTE" == "$WIKI_URL" ]] || fail "Workdir origin does not match wiki URL: $WORKDIR"
  log "Reusing existing workdir: $WORKDIR"
  git -C "$WORKDIR" fetch origin
  CURRENT_BRANCH="$(git -C "$WORKDIR" rev-parse --abbrev-ref HEAD)"
  git -C "$WORKDIR" pull --ff-only origin "$CURRENT_BRANCH"
else
  # Default mode: create a fresh wiki checkout for a clean one-shot publish.
  log "Cloning wiki repository..."
  if ! git clone "$WIKI_URL" "$WORKDIR"; then
    fail "Failed to clone wiki repository. Make sure GitHub Wiki is enabled and has an initial Home page."
  fi
fi

log "Syncing markdown files..."
# Replace only top-level markdown pages. Non-markdown files are left untouched.
# This keeps wiki page content aligned with the local draft directory.
find "$WORKDIR" -mindepth 1 -maxdepth 1 -type f -name '*.md' -exec rm -f {} +
find "$SOURCE_DIR" -mindepth 1 -maxdepth 1 -type f -name '*.md' -exec cp {} "$WORKDIR/" \;

git -C "$WORKDIR" add -A

if git -C "$WORKDIR" diff --cached --quiet; then
  # Exit quietly when the wiki repo already matches the local draft source.
  log "No wiki changes detected."
  if [[ "$DRY_RUN" -eq 1 || "$KEEP_WORKDIR" -eq 1 ]]; then
    log "Workdir: $WORKDIR"
  fi
  exit 0
fi

log "Creating commit..."
git -C "$WORKDIR" commit -m "$COMMIT_MESSAGE"

if [[ "$DRY_RUN" -eq 1 ]]; then
  # Dry-run mode is useful for inspecting the exact committed wiki state before push.
  log "Dry run complete. Review the wiki repository at: $WORKDIR"
  exit 0
fi

log "Pushing wiki changes..."
git -C "$WORKDIR" push origin HEAD
log "Wiki publish complete."

if [[ "$KEEP_WORKDIR" -eq 1 ]]; then
  log "Kept workdir: $WORKDIR"
fi
